### ISSUE TITLE
Static URL?

### ISSUE THREAD

**Issue by HendX** [CityofSantaMonica/GTFS#1]
Hi there! Would it be possible to publish the latest feed on a static URL (as in, one that doesn't change). It's hard to automatically check for new versions of the feed.

Perhaps you can keep it exactly as is with the naming, but also add a file called google_transit.zip or google_transit_latest.zip which is an exact copy of whichever is the latest version?

Thanks!

**Comment by thekaveman** [comment]
@HendX we have an update for you!

Please see http://gtfs.bigbluebus.com - we now publish a static URL for the "current" GTFS file, as well as GTFS-R (real-time).

**Comment by HendX** [comment]
Thanks @thekaveman - already updated on TransitFeeds.com, as well as adding the GTFS-realtime feeds!
