### ISSUE TITLE
Link to github is to directory in repository.

### ISSUE THREAD

**Issue by earino** [CityofSantaMonica/GTFS#2]
On http://gtfs.bigbluebus.com/#livemap it says:

     The source code is available on GitHub

But the link points to a subdirectory containing the protobuf code: https://github.com/CityofSantaMonica/gtfs.bigbluebus.com/tree/master/javascript-protobuf 

instead of https://github.com/CityofSantaMonica/gtfs.bigbluebus.com (or the appropriate directory.)

**Comment by kevinsmgov** [comment]
The second link you have is for the entire website. The first link is to the folder with example.js and the readme.md file so it made more sense to me to point people there who wanted to see how the live map code worked. I can add more to the readme.md file to make that clearer.

**Comment by earino** [comment]
Oh wow I completely missed that. An enhanced readme.md would definitely make a difference! Looking at the SaMo repo, I'm really impressed! I didn't know our city had this much open data!

**Comment by kevinsmgov** [comment]
Thank you. Between our GitHub repositories and [data.smgov.net](https://data.smgov.net/) I think we have made a good start. There are going to be some interesting enhancements in the next few months as well. Please let us know how it's working for you and any ideas and/or suggestions you have.
